version: "3.6"

services:
  influxdb:
    image: influxdb:1.7

  telegraf-1:
    image: telegraf:1.10
    command: --config-directory=/etc/telegraf/conf.d
    volumes:
      - ./telegraf-1/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./shared:/etc/telegraf/conf.d
    depends_on:
      - influxdb

  telegraf-2:
      image: telegraf:1.10
      command: --config-directory=/etc/telegraf/conf.d
      volumes:
        - ./telegraf-2/telegraf.conf:/etc/telegraf/telegraf.conf
        - ./shared:/etc/telegraf/conf.d
      depends_on:
        - influxdb
