apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf
  namespace: monitoring
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegraf
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf
subjects:
  - kind: ServiceAccount
    name: telegraf
    namespace: monitoring
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: telegraf
  apiGroup: rbac.authorization.k8s.io
