version: "3.6"

services:
  python:
    build:
      context: .
    command: /code/main.py
    volumes:
      - ./main.py:/code/main.py
    restart: always
    depends_on:
      - influxdb
      - mqtt

  chronograf:
    image: chronograf:1.7
    command: chronograf --influxdb-url=http://influxdb:8086
    ports:
      - 8888:8888

  influxdb:
    image: influxdb:1.7

  telegraf:
    image: telegraf:1.9
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
      - mqtt

  mqtt:
    image: eclipse-mosquitto:1.5
    ports:
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log
