apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-nodes
  namespace: monitoring
data:
  telegraf.conf: |
    [[outputs.influxdb_v2]]
      urls = ["http://influxdb.monitoring:9999"]

      organization = "InfluxData"
      bucket = "kubernetes"
      token = "secret-token"

    [[inputs.kubernetes]]
      url = "https://kubernetes.default.svc.cluster.local/api/v1/nodes/$NODE_NAME/proxy/"
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
