version: "2.4"

services:
  chronograf:
    image: chronograf:1.7
    command: chronograf --influxdb-url=http://influxdb:8086
    ports:
      - 8888:8888
    depends_on:
      influxdb:
        condition: service_healthy

  influxdb:
    image: influxdb:1.7
    healthcheck:
      test: bash -c "</dev/tcp/localhost/8086"
    volumes:
      - ./ddl.txt:/tmp/ddl.txt
      - ./dml.txt:/tmp/dml.txt
      - ./together.txt:/tmp/together.txt
