version: "2.4"

services:
  chronograf:
    image: chronograf:1.7
    command: chronograf --influxdb-url=http://influxdb:8086 --kapacitor-url=http://kapacitor:9092
    ports:
      - 8888:8888
    depends_on:
      influxdb:
        condition: service_healthy

  influxdb:
    image: influxdb:1.7
    healthcheck:
      test: bash -c "</dev/tcp/localhost/8086"

  kapacitor:
    image: kapacitor:1.5
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    volumes:
      - ./live-stream.tick:/tmp/live-stream.tick
      - ./historical-batch.tick:/tmp/historical-batch.tick
      - ./define-tasks.sh:/tmp/define-tasks.sh

  telegraf:
    image: telegraf:1.9
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
