version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ReallyStrongPassword1!"

  chronograf:
    image: chronograf:1.7
    command: chronograf --influxdb-url=http://influxdb:8086
    ports:
      - 8888:8888
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:1.9
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
      - sqlserver

  influxdb:
    image: influxdb:1.7
    healthcheck:
      test: bash -c "</dev/tcp/localhost/8086"
